@hostname = localhost
@port = 3000
@host = http://{{hostname}}:{{port}}
@contentType = application/json
@userId = 66de9576c52006c47b7bf8ad

### LIST 
GET {{host}}/users?limit=10&offset=0

### FIND ONE
GET {{host}}/users/{{userId}}

### Create
POST {{host}}/users
Content-Type: {{contentType}}

{
    "name": "hitesh",
    "email": "test@email.com",
    "phoneNumber": "+91123123123"
}

### UPDATE
PATCH {{host}}/users/{{userId}}
Content-Type: {{contentType}}

{
    "name": "Hitesh Joshi",
    "phoneNumber": "+91123123"
}